// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"time"
)

type AuthOps struct {
	Login    interface{} `json:"login"`
	Register interface{} `json:"register"`
}

type LastSeenCoordinateInput struct {
	Latitude  float64 `json:"latitude"`
	Longitude float64 `json:"longitude"`
}

type Mutation struct {
}

type NewUser struct {
	Name     string `json:"name"`
	Email    string `json:"email"`
	Password string `json:"password"`
}

type Query struct {
}

type TigerInput struct {
	Name               string                   `json:"name"`
	DateOfBirth        time.Time                `json:"dateOfBirth"`
	LastSeenTime       time.Time                `json:"lastSeenTime"`
	LastSeenCoordinate *LastSeenCoordinateInput `json:"lastSeenCoordinate"`
}