// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"time"

	"github.com/99designs/gqlgen/graphql"
)

type AuthOps struct {
	Login    interface{} `json:"login"`
	Register interface{} `json:"register"`
}

type Coordinate struct {
	Latitude  float64 `json:"latitude"`
	Longitude float64 `json:"longitude"`
}

type CoordinateInput struct {
	Latitude  float64 `json:"latitude"`
	Longitude float64 `json:"longitude"`
}

type CreateOps struct {
	CreateSighting *Sighting `json:"createSighting"`
	CreateTiger    *Tiger    `json:"createTiger"`
}

type ListOps struct {
	ListTigers    []*Tiger    `json:"listTigers"`
	ListSightings []*Sighting `json:"listSightings"`
}

type Mutation struct {
}

type NewUser struct {
	Name     string `json:"name"`
	Email    string `json:"email"`
	Password string `json:"password"`
}

type Query struct {
}

type SightingInput struct {
	TigerID    string           `json:"tigerID"`
	Coordinate *CoordinateInput `json:"Coordinate"`
	Image      *graphql.Upload  `json:"image,omitempty"`
}


type TigerInput struct {
	Name               string           `json:"name"`
	DateOfBirth        time.Time        `json:"dateOfBirth"`
	LastSeenTime       time.Time        `json:"lastSeenTime"`
	LastSeenCoordinate *CoordinateInput `json:"lastSeenCoordinate"`
}
