// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"time"

	"github.com/99designs/gqlgen/graphql"
)

type AuthOps struct {
	Login    interface{} `json:"login"`
	Register interface{} `json:"register"`
}

type CreateOps struct {
	CreateSighting *Sighting `json:"createSighting"`
	CreateTiger    *Tiger    `json:"createTiger"`
}

type LastSeenCoordinateInput struct {
	Latitude  float64 `json:"latitude"`
	Longitude float64 `json:"longitude"`
}

type ListOps struct {
	ListTigers    []*Tiger    `json:"listTigers"`
	ListSightings []*Sighting `json:"listSightings"`
}

type Mutation struct {
}

type NewUser struct {
	Name     string `json:"name"`
	Email    string `json:"email"`
	Password string `json:"password"`
}

type Query struct {
}

type SightingInput struct {
	TigerID            string                   `json:"tigerID"`
	LastSeenTime       time.Time                `json:"lastSeenTime"`
	LastSeenCoordinate *LastSeenCoordinateInput `json:"lastSeenCoordinate"`
	Image              *graphql.Upload          `json:"image,omitempty"`
}

type TigerInput struct {
	Name               string                   `json:"name"`
	DateOfBirth        time.Time                `json:"dateOfBirth"`
	LastSeenTime       time.Time                `json:"lastSeenTime"`
	LastSeenCoordinate *LastSeenCoordinateInput `json:"lastSeenCoordinate"`
}