// Code generated by MockGen. DO NOT EDIT.
// Source: bcrypt.go
//
// Generated by this command:
//
//	mockgen -source=bcrypt.go -destination=mock/bcrypt.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockBcryptInterface is a mock of BcryptInterface interface.
type MockBcryptInterface struct {
	ctrl     *gomock.Controller
	recorder *MockBcryptInterfaceMockRecorder
}

// MockBcryptInterfaceMockRecorder is the mock recorder for MockBcryptInterface.
type MockBcryptInterfaceMockRecorder struct {
	mock *MockBcryptInterface
}

// NewMockBcryptInterface creates a new mock instance.
func NewMockBcryptInterface(ctrl *gomock.Controller) *MockBcryptInterface {
	mock := &MockBcryptInterface{ctrl: ctrl}
	mock.recorder = &MockBcryptInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBcryptInterface) EXPECT() *MockBcryptInterfaceMockRecorder {
	return m.recorder
}

// ComparePassword mocks base method.
func (m *MockBcryptInterface) ComparePassword(hashedPassword, password string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ComparePassword", hashedPassword, password)
	ret0, _ := ret[0].(error)
	return ret0
}

// ComparePassword indicates an expected call of ComparePassword.
func (mr *MockBcryptInterfaceMockRecorder) ComparePassword(hashedPassword, password any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ComparePassword", reflect.TypeOf((*MockBcryptInterface)(nil).ComparePassword), hashedPassword, password)
}

// HashPassword mocks base method.
func (m *MockBcryptInterface) HashPassword(password string) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HashPassword", password)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// HashPassword indicates an expected call of HashPassword.
func (mr *MockBcryptInterfaceMockRecorder) HashPassword(password any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HashPassword", reflect.TypeOf((*MockBcryptInterface)(nil).HashPassword), password)
}
